caspar_health_processing:
  outputs:
    dev:
      dbname: main
      host: dwh4
      user: datauser
      pass: password
      port: 5432
      schema: public
      type: postgres
      threads: 4
  target: dev
